# Dependencies for projects USING this plugin are defined in Dependency.kt
# The dependencies declared here are exclusively for AlgoMate itself

[versions]
gradle-publish = "2.2.1"
kotlin = "2.2.0"
style = "3.0.0"
jagr = "0.11.0"

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
style = { id = "org.sourcegrade.style", version.ref = "style" }

[libraries]
jagr-gradle = { group = "org.sourcegrade", name = "jagr-launcher-gradle-plugin", version.ref = "jagr" }
